<?php

/**
 * @file
 * Contains hello_world.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hello_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hello_world module.
    case 'help.page.hello_world':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is my Hello World module') . '</p>';
      return $output;

    default:
  }
}

function hello_world_form_alter(&$form, $form_state, $form_id) {
	if($form_id == 'node_article_edit_form') {
		$form['options'] ['#open'] = TRUE;  //name of Promotion options in the kint was 'options'
	//kint($form);
	}
	$user = \Drupal::currentUser();
	if (!$user->hasPermission('administer content')) {
		$form['field_tags'] ['#access'] = FALSE;
	}
}