<?php

/**
 * @file
 * Contains eventbrite_formatter.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eventbrite_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eventbrite_formatter module.
    case 'help.page.eventbrite_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('EventBrite field formatter to turn an ID into an EventBrite form') . '</p>';
      return $output;

    default:
  }
}

function eventbrite_formatter_theme() {
	return array (
		'event_brite_form' => array('variables' => array('eventbrite_id' => array()),
		),
	);	
}